name: Continuous Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: 'latest'
          # Se han eliminado los inputs no válidos: service_account_key y export_default_credentials

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/challenge-repo/challenge-api:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/challenge-repo/challenge-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy challenge-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/challenge-repo/challenge-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 512Mi
