name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge-api:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy challenge-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/challenge-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 512Mi
